name: Build

on:
  push:
    branches:
      - '**' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set BUILD_VERSION
      run: echo "BUILD_VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))-b$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
    - name: BuildTools cache
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ secrets.CACHE_VERSION }}-${{ hashFiles('./.github/workflows/buildtools.sh') }}
        restore-keys: |
          ${{ runner.os }}-maven-${{ secrets.CACHE_VERSION }}-
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: BuildTools Java 17
      run: |
        sh ./.github/workflows/buildtools.sh java-17
    - name: Build
      run: |
        mvn clean package --batch-mode --also-make -Drevision=$BUILD_VERSION
        mv commandmanager-bukkit/target/commandmanager-*.jar ./
        mv commandmanager-bungee/target/commandmanager-*.jar ./
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: commandmanager
        path: |
          ./commandmanager-bukkit-*.jar
          ./commandmanager-bungee-*.jar